NYUCCL/psiTurk

doc/install.rst

(didn't work for me on Debian Wheezy)

delete package-based installation of virtualenvwrapper

---

psiturk/db.py

That's supposed to be "pip install mysql-python", not "pip mysql-python"

fixed error message

---

setup.py

@jhamrick's 82cb5555 on the dev branch is a better solution and will clobber this commit, but I'm targeting the master branch in case y'all want to get this released asap so people stop running into issues with the too-new psutil api:
https://groups.google.com/d/msg/psiturk/XooDMBg33Sg/-yG2UqVH0kYJ
https://groups.google.com/d/msg/psiturk/bjJXaMqk5O0/4LDHlNO8k7kJ
https://groups.google.com/d/msg/psiturk/tIDyusjzYIY/KkUSpA4Hj7gJ

specify psutil dependency <= 2.2.1

---

psiturk/amt_services.py
psiturk/command_line.py
psiturk/counter.py
psiturk/db.py
psiturk/experiment_server.py
psiturk/experiment_server_controller.py
psiturk/models.py
psiturk/psiturk_org_services.py
psiturk/psiturk_shell.py
test_psiturk.py

Misc. fixes from Wallace

---

psiturk/amt_services.py

get_workers now counts the total number of results for
a given hit, and then requests multiple pages of up to 100
assignemnts per page until all results are obtained.
Note, however, that the code is currently still limited to
returning workers from the first 20 hits.
Fixes #203

get_workers gets more than 100 workers/assignments

---

doc/conf.py

This makes the local build look just like things will look like

build docs in readthedocs theme

---

doc/command_line/hit.rst

Reflects fractional duration functionality introduced in #180. See also #137, #165.

Describe fractional duration functionality

---

doc/config/task_parameters.rst

We should probably also create a bug report for this too. Maybe the issue can be fixed in experiment.py

task parameters doc update

---

psiturk/psiturk_shell.py

This is a simple safe fix and I would just merge this straight up, but I'm kind of experimenting with my new powers by seeing if I can still create PRs and then merge my own PR.
Closes #237

add_bonus function searches db using uniqueid

---

psiturk/psiturk_shell.py

Tested, works for me... welcome to psiturk, status == credited!

Set status = credited when approving workers

---

psiturk/example/static/css/style.css
psiturk/example/templates/complete.html
psiturk/example/templates/default.html
psiturk/example/templates/thanks-mturksubmit.html
psiturk/example/templates/thanks.html

see also 1f9d16e6148b774fb4e11e78bb0149004f260513

nuking container-ad strings

---

psiturk/experiment.py

Quick fix for #244 (PsiTurk using old number of conditions)

always use current cond/counterbalance values from config

---

requirements.txt

Flask 0.12.1 allows range requests, allowing proper streaming and seeking for
videos.

bump Flask and Werkzeug versions

---

doc/config/server_parameters.rst
doc/configuration.rst
psiturk/default_configs/local_config_defaults.txt
psiturk/experiment_server.py

enh: add parameter to control gunicorn server timeout

---

psiturk/setup_example.py

Respect PSITURK_GLOBAL_CONFIG_LOCATION in setup-example

---

psiturk/utils.py

This method is safe if the previous output is provided.

Fixes 377 by parsing the json returned from httpbin.org.

---

psiturk/db.py
psiturk/psiturk_config.py
psiturk/psiturk_shell.py

Use sys.exit instead of exit

---

setup.py

Include dashboard and api subpackages in setup.py

---

doc/recording.rst
doc/retrieving.rst
psiturk/amt_services.py
psiturk/api/__init__.py
psiturk/experiment.py
psiturk/models.py
psiturk/psiturk_config.py
tests/conftest.py
tests/test_amt.py

same as previous pull request but using a different branch to follow GitHub flow

Changing dates to UTC

---

psiturk/psiturk_shell.py
psiturk/shell_help/hit.txt

Short commit to removing references to the outdated command dispose #406

Removes references to dispose

---

doc/install.rst

Added a short section on running psiturk in a virtual machine and a longer section about running psiturk in WSL.

Update install.rst for running psiturk on windows

---

psiturk/experiment_server_controller.py
psiturk/psiturk_shell.py
tests/test_psiturk_shell.py

Jacob lee 443 ps cleanup

---

psiturk/experiment_server_controller.py
psiturk/psiturk_shell.py
tests/test_psiturk_shell.py

Intended to fix issue https://github.com/NYUCCL/psiTurk/issues/443

443-ps_cleanup

---

psiturk/experiment.py
psiturk/experiment_server.py
psiturk/experiment_server_controller.py

- removes the http request and route to get ppid of server
- uses shutil to shutdown the process tree
- refactors the edge case for when ^C is entered in the psiturk-shell

Refactor server shutdown

---

psiturk/experiment.py
psiturk/psiturk_shell.py

Fixes issue https://github.com/NYUCCL/psiTurk/issues/451
- sets Cmd2 to output non-essential info (pfeedback) to standard output
- changes one call to pfeedback to perror
- cleans up minor PEP8 issue.

Issue 451: do_debug fix

---

psiturk/psiturk_config.py

Fixes typo

---

doc/migrating.rst
doc/tutorials/heroku.rst

@gureckis some small tweaks to your announcement. sphinx formatting to make the page not appear twice in the navbar, small typos, and putting your name at the top of the announcement. s'okay?

Proof announcement

---

CHANGELOG.md
doc/settings.rst
psiturk/default_configs/local_config_defaults.txt
psiturk/example/config.txt.sample
psiturk/version.py

facepalm, the default port for https is 443, not 80. change psiturk default.

default port should be 443

---

CODE_OF_CONDUCT.md

not been an issue but good to have, and adding to docs

created a code of conduct from github

---

CHANGELOG.md
psiturk/example/custom.py.sample
psiturk/user_utils.py
tests/conftest.py

Do not allow empty username or password!

Fix psiturk authorization

---

psiturk/default_configs/local_config_defaults.txt
psiturk/experiment_server.py

Fix errorlog lookup

---

setup.cfg
tests/conftest.py
tests/test_amt.py

See https://github.com/NYUCCL/psiTurk/pull/528#issuecomment-931879960

pin ciso8601 to v2.1.3

---

psiturk/dashboard/static/js/campaigns.js
psiturk/dashboard/static/js/hits.js
psiturk/dashboard/static/js/index.js
psiturk/dashboard/static/js/tasks.js
psiturk/dashboard/templates/dashboard/assignments.html
psiturk/dashboard/templates/dashboard/campaigns.html
psiturk/dashboard/templates/dashboard/hits.html
psiturk/dashboard/templates/dashboard/index.html
psiturk/dashboard/templates/dashboard/layouts/layout.html
psiturk/dashboard/templates/dashboard/tasks.html

- spinners as loading icons on each page that does a fetch_all (closes #512)
- highlight active page in nav bar

loading icons and active_page highlighting
