psiturk/psiturk_shell.py
It seems handy to be able to see what auto-computed bonuses your workers are set to receive.
Perhaps the output field name of "pending-bonus" or "computed-bonus" would be less confusing since all the other data in `worker list` comes from AWS, while the bonus exists in the psiTurk DB.
=> add computed bonus in worker list output

psiturk/experiment.py
Now catching only the ImportError that's caused by the absence of custom.py but re-raising all ImportErrors that are caused by screwed up imports _in_ custom.py and its dependencies.
=> Better exception handling with custom.py

psiturk/experiment.py
Best as I can tell (I'm still gettting my bearings in psiturk's codebase so apologies if I'm wrong) this doesn't actually do anything. sys.path.append(os.getcwd()) doesn't throw ImportErrors and at least in your whoops y'all example the contents of custom_models.py are imported in custom.py, not in experiment.py
=> remove superfluous code

psiturk/experiment.py
see http://flask.pocoo.org/docs/0.10/config/
Also: Any reason the cache timeout shouldn't also be user configurable (perhaps with a sensible default)?
=> cache control max age measured in seconds, not ms

psiturk/psiturk_shell.py
Since Amazon changed its pricing structure on July 22nd, it may be good to report the actual cost of HITs when you create them, rather than reporting the cost with the old 10% commission fee. The change made takes into consideration the number of assignments (20% for < 10 assignments, 40% for >= 10).
=> update total HIT cost based on new fees

doc/configure_databases.rst
From https://dev.mysql.com/doc/refman/5.0/en/connecting.html#idm140235558252992
> On Unix, MySQL programs treat the host name localhost specially, in a way that
> is likely different from what you expect compared to other network-based
> programs. For connections to localhost, MySQL programs attempt to connect to
> the local server by using a Unix socket file.
=> add note about using 127.0.0.1 for mysql hostname

psiturk/experiment_server_controller.py
Currently, when checking the server psiTurk searches through ALL user's
processes for psiturk server processes, and thus if a second user is
running a psiturk server it will find these processes and try to
communicate with them, causing an error. If psiturk only searches for
the current user's processes, multiple users should be able to
serve from the same server, as long as they use different ports.
=> ignore other users processes when checking server

psiturk/psiturk_js/psiturk.js
`.bind` (which was deprecated in jquery v1.7) can only attach handlers to
matching elements that already exist in the DOM. `.on`, on the other hand,
is dynamic and attaches to elements that may match in the future (and
detaches from elements that stop matching). Changing to `.on` allows a
class of 'continue' or 'previous' to be added to a button at a later time
so that it can act as a forward button.
`.on` needs to be anchored to a parent element that will receive the
bubbled event. the parent element should ideally be as close to the
targeted event elements as possible so decrease bubbling noise. i attached
it to the parent .instructionsnav container.
=> change instructionsnav click handler from `.bind` to `.on`

psiturk/example/templates/instructions/instruct-2.html, psiturk/example/templates/instructions/instruct-3.html
The 'previous' button within the instructionsnav example template had the
same id and value as the 'continue' button.
=> instructionsnav id and value fix

psiturk/example/templates/error.html, psiturk/experiment_errors.py, test_psiturk.py
Fixes #89 and adds a bunch of descriptions to go with each of the errors. There were a few errors that didn't seem to be used anywhere, so I didn't really know what description to put with them:
* intermediate_save
* ad_not_found
* template_unsafe
* in_debug
* unknown_error
I gave them empty strings for now but really there are I think two options which would be better:
1. Remove these errors since they are no longer used
2. If they should be kept in, give them a non-empty string for the description
=> Add descriptions for each of the errors

psiturk/example/templates/default.html
In the stroop example, the `default.html` page redirects people to the ad page. However, the ad page expects query string arguments, and thus just gives an error. This PR adds a little javascript to `default.html` so that it generates a random set of query string arguments for the ad url, just like you'd get if you ran `debug` from the psiturk command line.
This is particularly useful for directing collaborators to preview experiments that you have running on a server somewhere.
=> Generate a random debug string in default.html

doc/conf.py, doc/external_surveys.rst, doc/file_desc/static_folder.rst, doc/file_desc/templates_folder.rst, doc/index.rst, doc/recording.rst
Adds a new main page to the docs describing how use window messaging to integrate external survey tools such as Qualtrics. @gureckis as promised moon(s?) ago.
Also edits the sphinx conf.py so that the docs build.
Also also fixes some blank lines and spacing
=> Docs for how to integrate external survey tools such as Qualtrics

CONTRIBUTING.md
Just adding the protocol to make it an external link
=> Fixing the readthedocs link to be an external link

psiturk/db.py
MySQL defaults to closing connections that have been inactive for 8
hours, which will result in the “MySQL Server has gone away” error if
you have a long-term, low-traffic experiment (e.g., if you want to
leave a server up for a one-session-per-day experiment). Setting the
pool_recycle=3600 flag in the create_engine call forces SQLAlchemy to
hourly refresh DBAPI connections.
=> fixes "MySQL Server has gone away" error for long-term experiments

psiturk/experiment.py
This fixes #219. As disscussed in #219, Google Chrome userAgent strings
include the word Safari. Because of this, trying to exclude Safari also
excludes Google Chrome.
The value for Safari userAgent strings just includes Safari and not
Google Chrome. Therefore, this problem can be fixed by first checking if
both "Chrome" and "Safari" are in the userAgent string. If this is true,
then we do not want to exclude it, so we do nothing. If this check
returns False, then we still want to check to see if "Safari" is in the
userAgent string because that is what we want to exclude. If it is, then
we exclude it.
=> Adds browser_exclude_rule for Safari

psiturk/amt_services.py
get_workers now called boto's get_all_hits(). One consequence of this edit
is that hits returned are no longer sorted descending by creation date.
this will change the order that the returned workers appear in
Fixes #208
=> get_workers get all hits

psiturk/experiment_server.py, requirements.txt
gunicorn's `on_exit` is hooked so that it can be called when
the server is shut down via CTRL+C. Otherwise
there is no notification to the user that the server
has shut down until they hit `enter` and see that
the cmdloop prompt suddenly says "server off"
unfortunatley detection of ctrl+c can't be handled reliably
by psiturk_shell even by checking `server.is_server_running()`
because gunicorn shuts down its workers asynchronously and
therefore status will sometimes be read before, during, or after
everything has shutdown
requires gunicorn >= 19.0 though (when the on_exit hook was
implemented). Everything works with the most recent gunicorn (19.4.5)
Closes #229
=> notify user when ctrl-c kills experiment server

psiturk/db.py
openshift will host mysql or postgresql relational DBs for you, if you
add those cartridges. this commit tells db.py to use the first installed
openshift db it finds. note that it is theoretically possible to have
both postgresql and mysql addon cartridges installed at the same time.
don't do that, that would be silly.
No editing config.txt required -- the location of the openshift db can
change, so relying on the env vars is really the best way to go. and
it's not easy to integrate the env vars into config.txt.
See README at https://github.com/deargle/openshift-psiturk-cartridge for
an example of getting mysql up and running.
=> use openshift db cartridge, if one is installed

doc/amt_setup.rst, doc/configure_databases.rst, doc/openshift.rst, psiturk/amt_services.py
December 2015 AWS enabled IAM access control for Mturk. This commit
edits the error message to be DB-services specific. Right now it makes
users think that their credentials aren't good for anything, but
actually the message here is only triggered if RDB services can't be
accessed.
Other commits should maybe change other login messages too to be more
specific, but this is a start.
Sorry for the obscene length but at least the message is informative!
see [this group
thread](https://groups.google.com/forum/#!topic/psiturk/1nx8D-tsE74)
=> changing the error message for RDS connections for IAM users

psiturk/psiturk_js/psiturk.js
this stashes the mode in the db (live, sandbox, debug). this can be
helpful when doing analyses later down the line in case one needs to
distinguish between live and sandbox assignments in the db. the mode is
stored as part of the taskdata datastring
also, this fixes a neighboring bug where the full useragent string
wasn't actually being saved to the taskdata datastring by backbone
=> Record mode and full useragent string in backbone model

doc/config/server_parameters.rst, doc/config/shell_parameters.rst, doc/configuration.rst, psiturk/amt_services.py, psiturk/default_configs/local_config_defaults.txt, psiturk/example/static/css/style.css, psiturk/example/templates/closepopup.html, psiturk/example/templates/thanks-mturksubmit.html, psiturk/experiment.py, psiturk/experiment_server.py, psiturk/psiturk_shell.py
Okay here goes. This is functionality for toggling the use of the psiturk ad server. Look in the new comments in psiturk/default_configs/local_config_defaults.txt for an overview of the changes. See [this gist][the gist] for an example config. Here's a summary of the process:
1. You can say whether you want to use psiturk's ad server. Default is `true`.
2. If you don't, then just say so and also set an `ad_location` url in the config for the location of your psiturk ad route. This url should point to a proxy server running in front psiturk/gunicorn. I used nginx. See [the gist referenced above][the gist] for a config that works for psiturk (and for flask/gunicorn/nginx in general). Your proxy server will need to handle SSL. You will need to get your own certs right now if you want to do …
=> Use own ad server

MANIFEST.in
I've gone ahead and made a `conda` package out of this repo for distribution via the community-curated `conda-forge` channel. (If y'all want to help maintain it, that would be cool, but is unrelated.) We've started included links to license files in the conda builds themselves, but doing so requires that the license be in the manifest itself. If this pull gets incorporated into the next pypi version, that would let us include said link.
=> Adding a reference to the LICENSE

psiturk/psiturk_shell.py
I don't pretend to be expert in mac environments, but explicitly importing gnureadline fixes broken things
see #173
=> import gnureadline if available

psiturk/psiturk_shell.py
The following bugs and UX issues were noticed when creating a HIT
in the command line tool:
* Partial command input raises uncaught exception
Example Input: hit create 9
Now it queries for the remaining arguments.
* The regex to validate the reward per HIT fails on inputs like:
-10.00
3J55
J55
New stricter regex used, along with cast to float.
* Uncaught exception when duration can not be cast as a float, e.g.
when receiving a non-numeric string as float.
* The arguments passed to amt_services methods have been cast
to their numeric equivalents. My tests, and the documentation for
boto.mturk and amazon's amt API suggest this should be fine.
* Maybe the reward amount should be explicitly tested >= 0, though
I cannot think of a way that a negative value might pass through the regex filter.
=> Committing for testing. Bug Fixes and Improvements to Hit Creation

doc/config/hit_configuration.rst, doc/configuration.rst, psiturk/default_configs/local_config_defaults.txt, psiturk/experiment.py, test_psiturk.py
Fixes #90 though it doesn't do anything about toggling whether the instructions are shown or not. I figured that should probably be a separate PR. I also added tests to make sure that the toggle works as expected and either blocks or does not block participants from completing the experiment.
Note that this will still block participants who started the experiment but quit early, regardless of the setting of `allow_repeats`.
=> Allow repeat participants

psiturk/amt_services.py
Makes the `us_only` and `approve_requirement` settings in the configuration file have the intended effects.  Fixes #263.
=> Add qualification requirements to HIT type (Fixes #263)

psiturk/experiment.py, psiturk/models.py
If you use a version of psiturk with this code on a db that was created with an earlier version of the code, you will need to manually create the 'mode' column in your db. If you're still using `sqlite` and if your schema name is still `participants.db` and your table name is still `turkdemo` (those are the default), you can run this from the terminal:
```
sqlite3 participants.db
ALTER TABLE turkdemo ADD COLUMN mode VARCHAR(128);
<ctrl+d>
```
That same sql will work for mysql and psql, too.
=> Db mode column

doc/config/hit_configuration.rst, doc/config/shell_parameters.rst, doc/configuration.rst, psiturk/default_configs/local_config_defaults.txt, psiturk/experiment_server.py, psiturk/experiment_server_controller.py, psiturk/psiturk_shell.py
This branch contains several small features and improvements:
1. **Automatic bonus message**: adds a config option to write a bonus message that will be used whenever bonusing, so the psiturk user doesn't have to keep typing it. I chose "Thanks for participating!" as a default.
2. **Handling missing or duplicate submissions**: I sometimes encounter cases where I have 2 workers with status 4 for a single assignment. Often I get a message from one of the workers saying the MTurk signed them out automatically, or something of that sort. Ideally psiTurk would never set status to 4 without the HIT being sucessfully completed but as a quick fix I added code to make sure that if there are 2 submissions for an assignment, psiTurk checks which one is the true submission with mTurk and gives …
=> Approving, bonusing, and server improvements

psiturk/psiturk_shell.py
* Implemented dialog confirmation as private method: _confirmDialog
* Asks for confirmation before HIT is created. created if response resolves to 'yes'. if 'no' or 'n', aborts creation of HIT.
=> Added confirmation dialog to hit_create()

psiturk/psiturk_shell.py
Amazon has recently updated its worker interface. Among these changes is a change in the URL structure when searching for HITs:
e.g. OLD: https://www.mturk.com/mturk/searchbar?selectedSearchType=hitgroups&searchWords=SearchTerm1+SearchTerm2+SearchTerm3
NEW: https://worker.mturk.com/projects?filters[search_term]=SearchTerm1+SearchTerm2+SearchTerm3
This commit simply reformts the url being rendered to the psiturk user.
=> Change to Amazon MTurk HIT search URL

psiturk/psiturk_config.py
Two changes to psiturk_config.py were implemented in this commit.
* In some places, config file paths were constructed using string concatenation. This was changed to use os.path.join.
* Code cleanup, e.g. lines < 80 chars.
=> Changed psiturk_config.py to use os.path.join and code clean up.

doc/install.rst, doc/retrieving.rst, psiturk/amt_services_wrapper.py, psiturk/db.py, requirements.txt
Until now, it was necessary to manually install the `mysql-python` package if one wanted to save the data in a [MySQL database](https://psiturk.readthedocs.io/en/latest/configure_databases.html?highlight=sql#using-a-self-hosted-mysql-database-recommended). Unfortunately, getting `mysql-python` properly installed was a nightmare. And `mysql-python` has hasn't been updated since 2014.
`pymysql` is a pure python alternative, which is [actively maintained](https://github.com/PyMySQL/PyMySQL) and which can be installed without problems. With `pymysql`, psiturk and your MySQL database can be happy again.
(Fixes #97)
=> Get rid of the mysql-python dependency

psiturk/psiturk_shell.py
Status command is broken - looks like tally_hits was moved out of the class and a reference to it didn't get fixed.
Updated it to call update_hit_tally instead, seems to be working fine.
=> bf: reference to tally_hits should be update_hit_tally

requirements.txt
Passed test at 9806225fa3a5dbb2c64c86bc42067a77462f9d72 with `mysql --version
mysql  Ver 8.0.12 for osx10.14 on x86_64 (Homebrew)` and `SQAlchemy 1.2.15`.
=> later SQAlchamy is compatible with mysql 8.0

psiturk/experiment.py
Use the [Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) HTTP header instead of the [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) header to detect a participant's preferred language.  This allows language detection in recent versions of most common browsers that no longer include language preferences in the user agent string.
=> better language detection (fixes #270)

psiturk/amt_services_wrapper.py
This provides a large speedup when the requester has many hits
Also, remove trailing whitespace
=> Call _get_local_hitids() only once in _get_hits()

doc/amt_setup.rst
Related to issue discussed in #370.
Added a sentence in the documentation for being careful to link both requester and sandbox requester account to AWS account.
=> More details in "Creating an AMT Requester account"

.gitignore, psiturk/psiturk_shell.py, psiturk/shell_help/config.txt
This PR provides a basic implementation to fix #408.  I know the config commands are pretty self-explanatory, but this prevents the command line from displaying an error message.
=> Creates basic help for config

psiturk/default_configs/local_config_defaults.txt, psiturk/example/templates/exp.html
I didn't follow `contact_email_on_error` to see if you should be a quoted address or is a boolean flag. This is just a quick fix so the example will run in a browser.
=> 🐛 fix #412: jquery path typo, localhost=>127.0.0.1, contact_email_on_error

doc/heroku.rst
Commit instructions moved so people following the guide don't commit it by default. Added a note on ON_CLOUD and a googlable error you'd get if you forget to set it.
=> Heroku instructions warn about exposing database_url.

psiturk/experiment_server_controller.py
The method `kill_child_processes` had several bugs which apparently failed silently when running most of the time. However this method is only used to kill the child process of the shell process used to grep for the psiturk server processes in the method `is_server_running`.
I removed this `kill_child_processes` entirely, and altered the `is_server_running` method to avoid using a (platform dependent) set of operating system tools (grep, awk, ps). Instead it uses the cross-platform tools that shutil library already provides. In particular it uses `shutil.process_iter` to safely iterate through the processes in a way that avoids race conditions.
=> Fix bug in ExperimentServerController and improve cross-platform support

psiturk/example/templates/exp.html
This patch adds quotation marks around codeversion to ensure that it is properly interpreted as a string and updates the comments to remove duplication of 'a number indexing counterbalancing conditions.'
=> Fixes example

CHANGELOG.md, doc/settings.rst, psiturk/amt_services.py, psiturk/amt_services_wrapper.py, psiturk/psiturk_shell.py, psiturk/version.py, tests/test_amt.py, tests/test_psiturk_shell.py
fixed an inconsistency between shell usage of "allowlist-qualification-ids" and
and config file calling the same "require_quals", same for "blocklist" and "block_quals". Also, documentation incorrectly described the config file accepting "allowlist_qualification_ids", while it only actually accepted "require_quals." Standardized on "require" and "block" throughout. Maintained backwards compatibility except in shell usage since docopt
doesn't seem to allow it in the way it parses the usage string
=> standardize on require_quals and block_quals

CHANGELOG.md, psiturk/psiturk_shell.py
so that wrapper doesn't get checked if quiet until a psiturk_shell 
function asks for it
=> switch order of quiet and aws_wrapper check

psiturk/experiment_server.py
currently the Heroku set up requires all the files to be in the top level folder.  however some times it would be convenient to have multiple experiments in a single github folder and to swap between them.  this adds an option (None by default) to let you configure this.  the tip to use it would be, on Heroku, to change the `heroku_app.py` file so that you pass a directory to `exp.launch()`.  For example, if your experiment was in ./exp1 then `exp.launch("./exp1")`.  the `config.txt` should be placed inside exp1 folder in this instance as well as static, templates and the custom.py file.
=> adds and option on startup to move to a different subfolder

psiturk/experiment.py
**Note:** I haven't tested this outside of local `psiTurk` and Heroku.
See #482 for rationale. From my understanding, though, this ought to work with any `stdout`/`stderr` intercepting log platforms.
=> Adds StreamHandler to support Heroku-like logging

psiturk/models.py
The variable `outstring` defined in a `with` statement is used outside the scope of the `with` in `get_question_data` and `get_event_data`, resulting in question and event data both throwing "Error reading record" errors (the exception being "I/O operation on closed file") when running `download_datafiles` from the psiturk shell.
=> Fix scoping bug in download_datafiles

CHANGELOG.md, doc/settings.rst, psiturk/amt_services.py, psiturk/amt_services_wrapper.py, psiturk/example/advanced_quals.json.sample, psiturk/example/config.txt.sample, scripts/create_sample_config_from_defaults.py
Currently, the PsiTurk custom qualification feature only allows for binary has-this-qualification-been-granted support. However, it's not hard at all to abstract the qualification logic to allow for supplying a JSON file of more advanced qualification requirements, which would allow users to provide their own MTurk-formatted qualification tests with performance thresholds directly to the HITs, like seen in [this blog post](https://katherinemwood.github.io/post/qualifications/). 
I've been using this updated version of PsiTurk in all of my recently created HITs and it works wonderfully alongside a script I built to upload custom qualification tests to MTurk and return their ID. I've seen this issue crop up before (https://github.com/NYUCCL/psiTurk/issues/458) and the code is so simple to …
=> Add custom MTurk qualification support

psiturk/amt_services.py, psiturk/psiturk_config.py
also, set aws access key id from default session, in the event that it 
wasn't set in psiturk's config files but was set in ones that boto 
prefers
=> prefer aws creds set via env

CHANGELOG.md, psiturk/dashboard/__init__.py, psiturk/user_utils.py, tests/conftest.py
Dashboard will refuse to start if `secret_key` is missing or if no valid mturk credentials. Fixes obscure error message and fixes infinite redirect loop respectively.
=> Fix friendly dashboard denial

CHANGELOG.md, psiturk/api/__init__.py, psiturk/dashboard/__init__.py, psiturk/experiment.py, psiturk/models.py
overrides flask-api's default `handle_error`, which would just return a 
500 error for any exception
=> warn if not do_scheduler; fix if do_scheduler false; more verbose api error handler; fix update campaign goal

CHANGELOG.md, psiturk/amt_services_wrapper.py, psiturk/db.py, psiturk/psiturk_shell.py, tests/test_db.py, tests/test_psiturk_shell.py
Speeds up querying local HIT id's vastly, especially on AWS accounts with many participants. For example, my dashboard loaded the local HITs in about 8 seconds before this commit, and in <1 after this commit. 
Doesn't seem like there would ever be a case in which Participants would have a HIT Id not in the HIT Id table anyways, unless you're talking about really old backwards compatibility to before the HIT table would be a thing.
=> Remove getting local HIT id's from Participants table

CHANGELOG.md, doc/migrating.rst
By deferring the datastring column, we can skip loading in of the trial data JSON cells (which are generally massive), and only query them into a model on their first explicit reference from a Participant object. See [here](https://docs.sqlalchemy.org/en/14/orm/loading_columns.html) for more.
This cut my many-row queries on the Participants table down from 40+ seconds each to literally under 1. yay
=> Deferred datastring column for insane Participant query speedup

CHANGELOG.md, doc/settings.rst, psiturk/amt_services_wrapper.py, psiturk/default_configs/local_config_defaults.txt, psiturk/example/config.txt.sample, psiturk/experiment.py, psiturk/psiturk_config.py
Separate config entries for qualification ids for live and sandbox mode -- because a given qualification id never exists in both modes.
=> Feature: live and sandbox quals

psiturk/experiment.py, tests/test_psiturk.py
Fixed an issue where users could pass arbitrary Python code to be executed on the server to the mode HTTP arg
More information about this type of vulnerability: https://secure-cookie.io/attacks/ssti/
=> Fix SSTI vulnerability in ad and consent pages

psiturk/psiturk_config.py
1. The local config file text says that `table_name` is being deprecated in favor of `assignments_table_name` and that `assignments_table_name` is preferred if both defined. However, only `table_name` was being used. An entry into the backwards_compatibility list in psiturk_config.py was added for this.
2. In the psiturk_config.py loop through the backwards compatibilities, the section was being hard-coded to `Hit Configuration`. This prevented fix in (1) from taking effect. It also was preventing the backwards compatibility setting for the logfiles from taking effect.
=> Fix two backwards compatibility bugs

setup.cfg
=> bump pyopenssl to 22.0.0
